<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="SQABOG-TGP2735" ignored="0" name="CaseTest" tests="4" failures="4" timestamp="26 sep 2018 22:03:05 GMT" time="5.955" errors="0">
  <testcase name="loginBootstrap" time="0.104" classname="tests.CaseTests">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at tests.CaseTests.loginBootstrap(CaseTests.java:25)
at tests.Main.main(Main.java:38)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- loginBootstrap -->
  <testcase name="menuBootstrap" time="0.0" classname="tests.CaseTests">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at tests.CaseTests.menuBootstrap(CaseTests.java:45)
at tests.Main.main(Main.java:38)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- menuBootstrap -->
  <testcase name="registroSistema" time="0.001" classname="tests.CaseTests">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at tests.CaseTests.registroSistema(CaseTests.java:53)
at tests.Main.main(Main.java:38)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- registroSistema -->
  <testcase name="pruebaPosicion" time="0.0" classname="tests.CaseTests">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at tests.CaseTests.pruebaPosicion(CaseTests.java:61)
at tests.Main.main(Main.java:38)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- pruebaPosicion -->
</testsuite> <!-- CaseTest -->
